name: SPIC DATALAKE
values:
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: expires_in
    value: ''
  - key: token_type
    value: Bearer
  - key: id_token
    value: ''
  - key: refresh_expires_in
    value: ''
  - key: session_state
    value: ''
  - key: scope
    value: ''
  - key: url_bff
    value: ''
  - key: access_token_frontend
    value: ''
  - key: secret
    value: ''
  - key: url_base_keycloak
    value: ''
  - key: keycloak_realm
    value: ''
  - key: keycloak_metrics_client_id
    value: ''
  - key: keycloak_metrics_client_secret
    value: ''
  - key: ACCESS_TOKEN_METRICS
    value: ''
  - key: TOKEN
    value: ''
  - key: secret_keycloack
    value: ''
  - key: url_bff_certi
    value: ''
  - key: GOOGLE_API_KEY
    value: ''
  - key: GOOGLE_API_TOKEN
    value: ''
color: 0
